{{- if .Values.verticalPodAutoscaler.enable }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "deployment.name" $ }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    {{- toYaml . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "deployment.name" $ }}
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      maxAllowed:
        cpu: "400m"
        memory: "1000Mi"
{{- end }}
